# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build Xcode"
  lane: xcodebuild do
    xcodebuild(
     archive: true,
     archive_path: "./build-dir/NYTimes.xcarchive",
     scheme: "NYTimes",
     workspace: "NYTimes.xcworkspace"
   )
  end
  desc "Run SwiftLint"
  lane: swiftlint do 
  swiftlint(
    mode: :lint,
    output_file: "./swiftlint.result.json",
    reporter: "json",
    config_file: "./.swiftlint.yml",
    files: [
      "NYTimes/*"
    ],
    ignore_exit_status: true,
    quiet: true,
    strict: true
  )
  end
  desc "Run Test"
  lane:scan do
  scan(scheme: "NYTimes")
end
end
